version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 3

  logstash:
    image: docker.elastic.co/logstash/logstash:7.0.0
    ports:
      - "5555:5555"
    depends_on:
      ["elasticsearch"]

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    ports:
      - 5601:5601
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5602"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      ["elasticsearch"]

  apm-server:
    image: docker.elastic.co/apm/apm-server:6.3.0
    ports:
      - 8200:8200
    depends_on:
      ["elasticsearch", "kibana"]
