version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    container_name: stackflow-elastic
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 3


  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.6
    container_name: stackflow-kibana
    ports:
      - 5601:5601
    depends_on:
      ["elasticsearch"]

  apm:
    image: docker.elastic.co/apm/apm-server:6.8.6
    container_name: stackflow-apm
    ports:
      - 8200:8200
    depends_on:
      ["elasticsearch"]

